/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package Grocery;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class AppTest {
    @Test void checkCreditCard() {
        CreditCard CUT = new CreditCard(100.00);
        assertEquals(100.00,CUT.getBalance());
        CUT.debit(10.0);
        assertEquals(90.00,CUT.getBalance());
        CUT.credit(10.0);
        assertEquals(100.00,CUT.getBalance());
    }
    @Test void checkCashier() {
        CreditCard cc = new CreditCard(100);
        Cashier c = new Cashier();
        c.payment(cc,10);
        assertEquals(cc.getBalance(), 90);        
        assertEquals(c.payment(100,10), 90.00);
    }
}
